// ─────────────────────────────────────────────────────────────
//  HEIST PLANNER — the 15 jobs (+ the secret 16th).
//  Every map is 12×12. Check them with:  node tools/check-heist-levels.mjs
//  Guards: path = straight-line waypoints (ping-pong, or loop: true), pause = steps spent turning,
//          phase = start part-way round, vision = how far they see.
//  Cameras: sit on a tile, turn through `dirs`, `hold` steps each way. The HACKER on a C tile
//  switches off every camera and laser. Lasers (=) can blink: laser: { on, off, offset }.
// ─────────────────────────────────────────────────────────────
export const LEVELS = {
  1: {
    name: 'The Corner Shop', par: 28,
    tip: 'Plan the thief\'s route, then press GO. Grab the $ and get to the van (E) — unseen.',
    map: [
      '############',
      '#T....#....#',
      '#.##..#.##.#',
      '#.#...#..#.#',
      '#.#.###..#.#',
      '#......$.#.#',
      '#.#.###..#.#',
      '#.#...#..#.#',
      '#.##..#.##.#',
      '#.....#....#',
      '#E.........#',
      '############',
    ],
    guards: [{ path: [[7, 1], [7, 9]], pause: 2, vision: 3 }],
  },
  2: {
    name: 'Jewellers Row', par: 60,
    tip: 'Two guards now. Plants (H) hide you — use WAIT to let a guard walk past.',
    map: [
      '############',
      '#T...#.....#',
      '#....#.$...#',
      '#..H.#.....#',
      '#....###.###',
      '#..........#',
      '###.####...#',
      '#.....*#...#',
      '#.#####....#',
      '#......H...#',
      '#E.........#',
      '############',
    ],
    guards: [
      { path: [[6, 1], [10, 1], [10, 3], [6, 3]], loop: true, vision: 2 },
      { path: [[1, 5], [10, 5]], pause: 2, vision: 3, phase: 4 },
      { path: [[10, 9], [3, 9]], pause: 2, vision: 3 },
    ],
  },
  3: {
    name: 'The Bank Lobby', par: 34,
    tip: 'Cameras sweep and lasers blink. Watch their timing while you plan.',
    map: [
      '############',
      '#T.........#',
      '#.#######..#',
      '#.#.....#..#',
      '#.#..$..#..#',
      '#.#.....#..#',
      '#.###=###..#',
      '#..........#',
      '#.#######=##',
      '#..........#',
      '#E.........#',
      '############',
    ],
    laser: { on: 4, off: 3 },
    cameras: [{ x: 10, y: 3, dirs: ['down', 'left'], hold: 5, vision: 4 }],
    guards: [{ path: [[1, 9], [10, 9]], pause: 2, vision: 3 }],
  },
  4: {
    name: 'The Server Room', par: 20,
    tip: '💻 NEW: the HACKER. While she stands on a terminal (C) every camera and laser is OFF.',
    map: [
      '############',
      '#T.K..#C..E#',
      '#..........#',
      '#.....#....#',
      '##=====#####',
      '#..........#',
      '#...$......#',
      '#..........#',
      '###===######',
      '#..........#',
      '#E.........#',
      '############',
    ],
    cameras: [{ x: 10, y: 7, dirs: ['left', 'up'], hold: 4, vision: 6 }],
  },
  5: { bonus: true, name: 'Safe Cracker', tip: 'Tap when the dial hits the green notch — crack as many safes as you can!' },
  6: {
    name: 'Warehouse 13', par: 30,
    tip: '💪 NEW: the MUSCLE smashes locked doors (D). Once it\'s smashed, anyone can walk through.',
    map: [
      '############',
      '#T.M.#.....#',
      '#....D..$..#',
      '#....#.....#',
      '##D###.....#',
      '#....#######',
      '#..........#',
      '#.####.###.#',
      '#.#..#.#*#.#',
      '#.#....#.#.#',
      '#E.........#',
      '############',
    ],
    guards: [
      { path: [[6, 1], [10, 1], [10, 3], [6, 3]], loop: true, vision: 2 },
      { path: [[1, 6], [10, 6]], pause: 3, vision: 3 },
    ],
  },
  7: {
    name: 'Casino Floor', par: 40,
    tip: 'Guards don\'t care about computers — the hacker only stops cameras and lasers.',
    map: [
      '############',
      '#T.K.....#E#',
      '#........#.#',
      '#.P.P.P..#.#',
      '#........#C#',
      '#.P.P.P....#',
      '#...........',
      '##=####=####',
      '#....$.....#',
      '#.H......*.#',
      '#E.........#',
      '############',
    ].map((r) => r.padEnd(12, '#').slice(0, 11) + '#'),
    cameras: [{ x: 5, y: 9, dirs: ['left', 'right'], hold: 4, vision: 5 }],
    guards: [
      { path: [[1, 2], [8, 2]], pause: 2, vision: 3 },
      { path: [[8, 6], [1, 6]], pause: 2, vision: 3, phase: 3 },
    ],
  },
  8: {
    name: 'The Gallery', par: 30,
    tip: 'The full crew. Hacker, muscle and thief all have to reach a van.',
    map: [
      '############',
      '#T.M..#C..E#',
      '#.....#..K.#',
      '#.....#....#',
      '##D#########',
      '#....=.....#',
      '#.P..=..P..#',
      '#....=.....#',
      '#....=..$..#',
      '#.H..=.....#',
      '#E...=.....#',
      '############',
    ],
    guards: [{ path: [[6, 5], [10, 5], [10, 10], [6, 10]], loop: true, vision: 3 }],
  },
  9: {
    name: 'Diamond Exchange', par: 35,
    tip: 'Two loot bags this time — the thief needs both.',
    map: [
      '############',
      '#T.M.#K...E#',
      '#....#...C.#',
      '#....#.....#',
      '##D###=#####',
      '#....#.....#',
      '#.$..D..H.$#',
      '#....#.....#',
      '####=####=##',
      '#..*.......#',
      '#E........E#',
      '############',
    ],
    guards: [
      { path: [[6, 5], [10, 5], [10, 7], [6, 7]], loop: true, vision: 2 },
      { path: [[1, 9], [10, 9]], pause: 2, vision: 3 },
    ],
  },
  10: { bonus: true, name: 'Safe Cracker II', tip: 'Faster dials, bigger payouts!' },
  11: {
    name: 'Train Yard', par: 56,
    tip: 'Guards pace the platforms. Timing is everything.',
    map: [
      '############',
      '#T.K.M.....#',
      '#..........#',
      '#.########.#',
      '#.#..$...#.#',
      '#.#......D.#',
      '#.#.####.#.#',
      '#.D......#.#',
      '#.########.#',
      '#....C.....#',
      '#E........E#',
      '############',
    ],
    guards: [
      { path: [[1, 2], [10, 2]], pause: 2, vision: 4 },
      { path: [[3, 4], [8, 4]], pause: 2, vision: 3 },
    ],
    cameras: [{ x: 10, y: 9, dirs: ['left', 'up'], hold: 6, vision: 5 }],
  },
  12: {
    name: 'Penthouse Suite', par: 33,
    tip: 'Plants are your friends. So is patience.',
    map: [
      '############',
      '#T.K.#E....#',
      '#....#.....#',
      '#M...D..H..#',
      '#....#.....#',
      '##=###.###D#',
      '#..H.....#.#',
      '#........#$#',
      '#.P..P...#.#',
      '#....C.....#',
      '#E.........#',
      '############',
    ],
    laser: { on: 5, off: 3 },
    guards: [
      { path: [[6, 2], [10, 2], [10, 4], [6, 4]], loop: true, vision: 3 },
      { path: [[1, 7], [8, 7]], pause: 3, vision: 3 },
    ],
    cameras: [{ x: 8, y: 9, dirs: ['up', 'left'], hold: 5, vision: 5 }],
  },
  13: {
    name: 'The Mint', par: 23,
    tip: 'The hacker has to pick the perfect moment to leave her terminal.',
    map: [
      '############',
      '#T.M...#K.E#',
      '#......#C..#',
      '#......#...#',
      '###D####=###',
      '#..........#',
      '#.P.P.P.P..#',
      '#..........#',
      '#=##########',
      '#..$...*...#',
      '#E.........#',
      '############',
    ],
    guards: [
      { path: [[1, 5], [10, 5]], pause: 2, vision: 3 },
      { path: [[10, 7], [1, 7]], pause: 2, vision: 3, phase: 6 },
    ],
    cameras: [{ x: 10, y: 9, dirs: ['left', 'up'], hold: 5, vision: 6 }],
  },
  14: {
    name: 'Federal Reserve', par: 47,
    tip: 'Three guards, two doors, one chance.',
    map: [
      '############',
      '#T.K.M.....#',
      '#..........#',
      '#.##D##=##.#',
      '#.#.....#..#',
      '#.#..$..#C.#',
      '#.#.....#..#',
      '#.###D###..#',
      '#..........#',
      '#..H....H..#',
      '#E........E#',
      '############',
    ],
    guards: [
      { path: [[1, 2], [10, 2]], pause: 2, vision: 3 },
      { path: [[3, 4], [7, 4], [7, 6], [3, 6]], loop: true, vision: 2 },
      { path: [[1, 8], [10, 8]], pause: 2, vision: 4, phase: 4 },
    ],
  },
  15: {
    name: 'The Crown Vault', par: 37,
    tip: 'The biggest job of all. Get everyone out — every step counts.',
    map: [
      '############',
      '#T.M....#KE#',
      '#.......#.C#',
      '#.......D..#',
      '####=####.##',
      '#....H.....#',
      '#.##.###.#.#',
      '#.#$...#.#.#',
      '#.####D#.#.#',
      '#...*......#',
      '#E........E#',
      '############',
    ],
    laser: { on: 6, off: 2 },
    guards: [
      { path: [[1, 5], [10, 5]], pause: 2, vision: 3 },
      { path: [[10, 9], [1, 9]], pause: 2, vision: 3, phase: 7 },
      { path: [[8, 5], [8, 9]], pause: 2, vision: 3, phase: 2 },
    ],
    cameras: [{ x: 10, y: 6, dirs: ['left', 'down'], hold: 4, vision: 4 }],
  },
  16: {
    name: '★ THE ROYAL TREASURY ★', par: 25,
    tip: 'Only the flawless get this far. Somewhere inside waits the greatest prize of all…',
    secret: true,
    map: [
      '############',
      '#T.K.M.....#',
      '#.....C....#',
      '##=######=##',
      '#....#.....#',
      '#....D..H..#',
      '#....#.....#',
      '######.#####',
      '#....#.#...#',
      '#.P..#.#.P.#',
      '#.....V....#',
      '############',
    ],
    guards: [
      { path: [[6, 4], [10, 4], [10, 6], [6, 6]], loop: true, vision: 2 },
      { path: [[1, 8], [4, 8]], pause: 2, vision: 2 },
      { path: [[10, 8], [8, 8]], pause: 2, vision: 2, phase: 1 },
    ],
  },
};
export const levelDef = (n) => LEVELS[n] || LEVELS[15];
